spring:
  redis:
    host: 122.51.51.150
    port: 9998
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负数）
        max-idle: 8 #连接池的最大空闲连接（使用负值表示没有限制）
        max-wait: 30 #最大阻塞等待时间
        min-idle: 0 #最小空闲连接
#    database: 0
#    password: 123456


